var num = 8;
var string = "Hello";
var boolean = false;
var arr = ["Hello", "Good Bye"];
var newArr = new Array("Hello2", "Good Bye2");
console.log(num);
console.log(string);
console.log(boolean);
console.log(arr);
console.log(newArr);
